uint16 navboard_seq
uint16[3] acc
int16[3] gyro
uint16 unk1
uint16 unk2
byte   us_echo_high_bit
uint16 us_echo
uint16 us_echo_start
uint16 us_echo_end
uint16 us_association_echo
uint16 us_distance_echo
uint16 us_courbe_temps
uint16 us_courbe_valeur
uint16 unk3
uint16 us_number_echo
uint16 unk4
uint32 us_sum_echo
uint16 us_initialized
uint16 unk5
uint16 unk6
uint16 unk7
int16[3] mag
uint16 unk8 	


